name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to EC2 using SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script_stop: true
        script: |
          cd /home/ubuntu
          if [ ! -d "port_cctv/.git" ]; then
            echo "Git repository not found. Cloning..."
            rm -rf port_cctv
            git clone https://github.com/gyuminiai82/cctv.git port_cctv
          fi
          cd port_cctv
          git pull origin main
          docker compose up -d --build
          docker image prune -f
